export default function Spacer() {
    return (
        <div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
            <div>x</div>
        </div>
    )
}